title = "RANTA - Coding, Hacking, Teaching and more"
description = "A page from Lukas Zurschmiede aka LukyLuke_ch about all things like Hacking, Printing, Coding, Claiming, and so on."
baseurl = "//ranta.ch/"
languageCode = "de-ch"
defaultContentLanguage = "de"
theme = "hugo-redlounge"
buildFuture = true
buildExpired = true
disable404 = true

[params]
	sidebartitle = "Ranta"
	sidebartagline = "Coding, Hacking, Teaching, Robotics, Security and more"
	nocomment = true
	lightbox = false
	sidebarphoto = "/page/ranta.jpg"
	categoriescss = "/css/ranta-changes.css"
	author = "Lukas Zurschmiede aka LukyLuke_ch"


[[menu.main]]
	name = "Articles"
	url = "/posts"

[[menu.main]]
	name = "Tutorials"
	url = "/tutorials"

[[menu.main]]
	name = "Projects"
	url = "/projects"


[[menu.social]]
	pre = "<i class='fa fa-twitter'></i>"
	url = "http://www.twitter.com/ranta_plan"
	identifier = "twitter"

[[menu.social]]
	pre = "<i class='fa fa-github'></i>"
	url = "http://www.github.com/LukyLuke"
	identifier = "github"
